### ISSUE TITLE
Add Seek method based on timestamp

### ISSUE THREAD

**Issue by marcocappolimases** [masesgroup/DataDistributionManager#22]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a channel seek method based on timestamp and not on offset.

**Describe the solution you'd like**
Implement a `Seek(DateTime dt)` method that seeks the channel using the _timestamp_ of the messages on _channel_ to set the reading offset.

**Describe alternatives you've considered**
No alternatives was considered.

**Additional context**
N/A

**Comment by mariomastrodicasa** [comment]
@marcocappolimases as stated in https://github.com/masesgroup/DataDistributionManager/issues/21#issuecomment-829898345, you are proposing a method which can accept negative values. The same approach can be applied to the `Seek` method proposed in this issue. One drawback with the actual implementation of `Seek` with negative values is that backends ([librdkafka](https://github.com/edenhill/librdkafka/tree/master), [OpenDDS](https://github.com/objectcomputing/OpenDDS/tree/master)) uses negative values for their internal purposes and specific negative values have well-known behavior. Since real offsets are positive monotonic incremental values and negative values are only special, I propose to change the signature of the `Seek` to add an optional parameter which defines if the offset is _Absolute_ or _Relative_, so it is possible to distinguish when a negative value refers to something in the past of the data stream or it is a special value. The same behavior can be applied to the `Seek` method that accepts a timestamp. 
In the issue you proposed a `DateTme` type which is undoubtedly related to .NET (C#). Both C# and Java implementations are wrappers around the C++ implementation: in https://github.com/masesgroup/DataDistributionManager/issues/21#issuecomment-831934797 there is a proposal about timestamp, but the low layer measures the timestamp as milliseconds from epoch (UTC) and the base type is something similar to the offset one. At C++ level the problem will be to distinguish between `Seek` method for offset and timestamp: my idea to solve this inchoerence is to add another optional parameter which defines which kind of input is receiving the `Seek` method. The final signature will be something like the following one:

```c++

typedef enum class DDM_SEEKCONTEXT
{
	OFFSET = 0x1,	   /**< Seek on offset */
	TIMESTAMP = 0x2,   /**< Seek on timestamp */
} DDM_SEEKCONTEXT;

typedef enum class DDM_SEEKKIND
{
	ABSOLUTE = 0x1,	   /**< Absolute seek */
	RELATIVE = 0x2,   /**< Relative seek */
} DDM_SEEKKIND;

virtual OPERATION_RESULT SeekChannel(CHANNEL_HANDLE_PARAMETER, int64_t position, DDM_SEEKCONTEXT context = DDM_SEEKCONTEXT::OFFSET, DDM_SEEKKIND kind = DDM_SEEKKIND::ABSOLUTE) = 0;
```
The previous implementation will be open for further extensions, adding more values to `DDM_SEEKCONTEXT` and `DDM_SEEKKIND`, without changing again the low level interface.

**Comment by marcocappolimases** [comment]
@mariomastrodicasa the solution seams optimal for C++.
I think that the implementation I proposed in the _Issue_ can be used to call transparently both an absolute or a relative seek.
